[package]
name = "voxel"
version = "0.1.0"
authors = ["luca <b.lucab1211@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_flycam = "*"
rand = "0.8.0"
noise = "0.7.0"
