[package]
<<<<<<< HEAD
name = "voxel"
=======
name = "space_shooter"
>>>>>>> d67640531502497c9f0425e7a53dcb5b10235b55
version = "0.1.0"
authors = ["luca <b.lucab1211@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
=======
bevy = "0.4.0"
rand = "0.8.0"
>>>>>>> d67640531502497c9f0425e7a53dcb5b10235b55
